openapi: 3.0.0
info:
  title: Care Worker API
  version: 1.0.0

servers:
  - url: http://localhost:3000/api

paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                role:
                  type: string
                  enum: [worker, admin]
      responses:
        "201":
          description: User created

  /auth/login:
    post:
      summary: Login and get JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Returns JWT token

  /auth/workers:
    get:
      summary: Get all workers
      security:
        - bearerAuth: []
      responses:
        "200":
          description: List of workers

  /residents:
    get:
      summary: Get all residents
      security:
        - bearerAuth: []
      responses:
        "200":
          description: List of residents
    post:
      summary: Create resident
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                dob:
                  type: string
                room:
                  type: string
                care_plan:
                  type: string
      responses:
        "201":
          description: Resident created

  /residents/{id}:
    get:
      summary: Get resident by ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Resident details
    put:
      summary: Update resident
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                room:
                  type: string
                care_plan:
                  type: string
                dob:
                  type: string
      responses:
        "200":
          description: Updated
    delete:
      summary: Delete resident (admin only)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Deleted

  /activities:
    get:
      summary: Get all activities
      security:
        - bearerAuth: []
      responses:
        "200":
          description: List of activities
    post:
      summary: Create new activity
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                resident_id:
                  type: integer
                worker_id:
                  type: integer
                activity_type:
                  type: string
      responses:
        "201":
          description: Activity created

  /activities/{id}/notes:
    get:
      summary: Get activity notes
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Notes list
    post:
      summary: Add activity note
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                note:
                  type: string
                resident_id:
                  type: integer
                activity_id:
                  type: integer
      responses:
        "201":
          description: Note added

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
